name: Sync to Github

params:
  incremental:
    default: true

triggers:
  push:
    branches:
      - master

strategy:
  fast-fail: false

jobs:
  sync-job:
    image: olivr/copybara:latest

    steps:
      - uses: checkout
        inputs:
          fetch-depth: 0

      - id: setup-ssh
        run: |
          # 2.1 安装基础工具 (官方镜像里可能缺 ssh)
          apt-get update && apt-get install -y openssh-client git

          # 2.2 启动 ssh agent
          eval $(ssh-agent -s)

          # 2.3 写入私钥 (从 CI 变量里读取)
          echo "${{secrets.GITHUB_SSH_KEY}}" | tr -d '\r' | ssh-add -

          # 2.4 配置 known_hosts，防止第一次连接弹出 yes/no 询问
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # 2.5 配置 Git 身份
          git config --global user.email "hi@zhaode.wang"
          git config --global user.name "wangzhaode"

      # 3. 执行同步
      - id: run-sync
        run: |
          copybara copy.bara.sky default --force