name: Sync to Github

params:
  incremental:
    default: true

triggers:
  merge_request:
    target-branches:
      - main
    types:
      - merged

strategy:
  fast-fail: false

jobs:
  sync-job:
    image: alios-8u

    steps:
      - uses: checkout
        inputs:
          fetch-depth: 0
          ref: main

      - uses: setup-env
        inputs:
          java-version: '21'

      - id: sync-to-github
        run: |
          apt-get update && apt-get install -y openssh-client git curl
          eval $(ssh-agent -s)
          echo "${{secrets.GITHUB_SSH_KEY}}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          chmod +x ./sync.sh
          ./sync.sh