name: Sync from Github

params:
  incremental:
    default: true

triggers:
  schedule:
    - cron: "0 6 * * *"

strategy:
  fast-fail: false

jobs:
  reverse-sync-job:
    image: alios-8u

    steps:
      - uses: checkout
        inputs:
          fetch-depth: 0
          ref: master

      - uses: cache@1.0.0
        inputs:
          key: copybara-cache
          path: /root/copybara
          scope: pipeline
          on-failure: retain
          ignore-broken-symlink: true

      - uses: setup-env
        inputs:
          java-version: '21'

      - uses: setup-github-proxy

      - id: reverse-sync-from-github
        run: |
          eval $(ssh-agent -s)
          echo "${{secrets.GITHUB_SSH_KEY}}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "external@contributor.com"
          git config --global user.name "External Contributor"

          git checkout master
          git pull origin master
          BEFORE_HASH=$(git rev-parse HEAD)
          echo "Base Hash (master): $BEFORE_HASH"

          git branch -D copybara_import_temp || true
          chmod +x ./release_scripts/copybara_sync.sh
          ./release_scripts/copybara_sync.sh --reverse

          git checkout master
          AFTER_HASH=$(git rev-parse HEAD)
          echo "Sync Hash (tmp): $AFTER_HASH"

          AFTER_HASH=$(git rev-parse HEAD)
          if git show-ref --verify --quiet refs/heads/copybara_import_temp; then
              echo "✅ Copybara fetched changes to temp branch. Attempting FF merge..."
              if git merge --ff-only copybara_import_temp; then
                  echo "Merge success. Pushing to internal..."
                  git remote set-url origin git@gitlab.alibaba-inc.com:zhaode.wzd/copybara-test-internal.git
                  ssh-keyscan gitlab.alibaba-inc.com >> ~/.ssh/known_hosts
                  git pull origin master --rebase
                  git push origin master
              else
                  echo "❌ Error: Cannot fast-forward. History diverged!"
                  exit 1
              fi
          else
              echo "✅ No changes synced from GitHub."
          fi