name: Sync from Github

params:
  incremental:
    default: true

triggers:
  schedule:
    - cron: "0 6 * * *"

strategy:
  fast-fail: false

jobs:
  reverse-sync-job:
    image: alios-8u

    steps:
      - uses: checkout
        inputs:
          fetch-depth: 0
          ref: master

      - uses: cache@1.0.0
        inputs:
          key: copybara-cache
          path: /root/copybara
          scope: pipeline
          on-failure: retain
          ignore-broken-symlink: true

      - uses: setup-env
        inputs:
          java-version: '21'

      - uses: setup-github-proxy

      - id: reverse-sync-from-github
        run: |
          eval $(ssh-agent -s)
          echo "${{secrets.GITHUB_SSH_KEY}}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "external@contributor.com"
          git config --global user.name "External Contributor"

          git checkout master
          git pull origin master
          BEFORE_HASH=$(git rev-parse HEAD)
          echo "Base Hash (master): $BEFORE_HASH"

          git checkout -B sync_tmp_branch
          chmod +x ./release_scripts/copybara_sync.sh
          ./release_scripts/copybara_sync.sh --reverse

          git checkout master
          AFTER_HASH=$(git rev-parse HEAD)
          echo "Sync Hash (tmp): $AFTER_HASH"

          AFTER_HASH=$(git rev-parse HEAD)
          if [ "$BEFORE_HASH" != "$AFTER_HASH" ]; then
              echo "Changes detected (Hash changed from $BEFORE_HASH to $AFTER_HASH)."
              if [ -n "$(git diff --stat origin/master master)" ]; then
                  echo "Pushing changes to internal GitLab..."
                  git remote set-url origin git@gitlab.alibaba-inc.com:AliNN/AliNNPrivate.git
                  ssh-keyscan gitlab.alibaba-inc.com >> ~/.ssh/known_hosts
                  git pull origin master --rebase
                  git push origin master
              else
                  echo "False alarm: Hash changed but effectively no content diff (possibly empty commit). Skipping push."
              fi
          else
              echo "No changes synced. (Ignored commits strictly touching .github/ or apps/)"
          fi
          git branch -D sync_tmp_branch